export const EVENTS = {
  JOIN_QUEUE: 'JOIN_QUEUE',
  ROOM_UPDATE: 'ROOM_UPDATE',
  START_SESSION: 'START_SESSION',
  SIGNAL: 'SIGNAL',
  LEAVE_ROOM: 'LEAVE_ROOM',
  TOGGLE_READY: 'TOGGLE_READY',
  MUTE_PARTICIPANT: 'MUTE_PARTICIPANT',
  MAKE_MUTE: 'MAKE_MUTE',
  FLAG_PARTICIPANT: 'FLAG_PARTICIPANT',
  PARTICIPANT_REMOVED: 'PARTICIPANT_REMOVED',
  SESSION_ENDING: 'SESSION_ENDING',
  SESSION_DISSOLVED: 'SESSION_DISSOLVED',
  SEAT_CLAIMED: 'SEAT_CLAIMED',
  SEAT_UPDATE: 'SEAT_UPDATE',
  HOST_TRANSFERRED: 'HOST_TRANSFERRED',
} as const;

export type EventKey = keyof typeof EVENTS;
